version: 1
builder:
  configs:
  - platform: ios
    scheme: PackageResources

  - platform: macos-spm
    scheme: PackageResources

  - platform: macos-xcodebuild
    scheme: PackageResources

  - platform: tvos
    scheme: PackageResources

  - platform: watchos
    scheme: PackageResources

  - platform: ios
    scheme: PackageResourcesCore

  - platform: macos-spm
    scheme: PackageResourcesCore

  - platform: macos-xcodebuild
    scheme: PackageResourcesCore

  - platform: tvos
    scheme: PackageResourcesCore

  - platform: watchos
    scheme: PackageResourcesCore

  - documentation_targets:
    - PackageResources
    - PackageResourcesCore
